name: Dockerized App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Start app + test stack
        run: docker compose up -d

      - name: Run tests in eatest
        run: docker exec eatest dotnet test /src/EAAppTest/EAAppTest.csproj --logger:trx --no-build --configuration Release

      - name: Copy test results from container
        run: |
          mkdir -p test-results
          docker cp eatest:/src/EAAppTest/TestResults test-results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/TestResults/*.trx

      - name: Show test container logs on failure
        if: failure()
        run: docker logs eatest

      - name: Show selenium hub logs on failure
        if: failure()
        run: docker logs selenium-hub
